version: '2'
services:
  angular: 
    build: public
    ports:
      - "3000:3000" 

  server: 
    build: server
    ports:
      - "57022:57022" 

  database:
    image: mongo
    ports:
      - "27017:27017" 