version: '2'
services:
  angular: 
    container_name: angularApp
    build: public
    ports:
      - "3000:3000" 

  server: 
    container_name: webServer
    build: express-server
    ports:
      - "3001:3001" 
    links: 
     - database

      
  mongodata:  
    image: mongo
    volumes:
      - /data/db
    command: --break-mongo

  database:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017" 
    volumes_from:
      - mongodata
    command: --smallfiles --rest


