FROM microsoft/iis
SHELL ["powershell"]

RUN Install-WindowsFeature NET-Framework-45-ASPNET ; \  
    Install-WindowsFeature Web-Asp-Net45

RUN mkdir -p /AbsaExerciseServer
COPY /AbsaExerciseServer/AbsaExerciseServer /AbsaExerciseServer  
RUN Remove-WebSite -Name 'Default Web Site'  
RUN New-Website -Name 'absaServer' -Port 57023 \  
    -PhysicalPath 'c:\AbsaExerciseServer' -ApplicationPool '.NET v4.5'

EXPOSE 57023

CMD ["ping", "-t", "localhost"] 
